name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Install dependencies and test for react-ui
      run: |
        cd src/apps/react-ui
        npm ci
        npm test

    - name: Install dependencies and test for terminal
      run: |
        cd src/apps/terminal
        npm ci
        npm test
